# -*- coding: utf-8 -*-
"""week Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15E2n8yrE-1KpRGW3rjNjBexc_8HQ12K5

## Python week 02
"""

# 設定課程名稱變數
course_name = "Python 程式設計基礎"

# 顯示歡迎訊息
print("歡迎來到：", course_name)

"""## Mission 2 : 變數與資料型態"""

# 宣告不同型態的變數
student_count = 60          # 整數 (int)
average_sleep_hours = 6.7   # 浮點數 (float)
course_name = "資訊管理"    # 字串 (str)
has_missing_value = True    # 布林值 (bool)

# 檢查變數型態
print("student_count 型態:", type(student_count))
print("average_sleep_hours 型態:", type(average_sleep_hours))
print("course_name 型態:", type(course_name))
print("has_missing_value 型態:", type(has_missing_value))

